/**
 * Script para traducir nombres y campos de ejercicios del dataset (EN → ES)
 * usando diccionarios de términos de fitness.
 * No requiere API key.
 *
 * Uso: node scripts/translateExercises.js
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const INPUT_JSON = path.resolve(__dirname, '../src/data/datasetExercises.json');

const EXERCISE_NAME_TRANSLATIONS = {
  // Términos compuestos (ordenados de más específicos a más generales)
  'bench press': 'press de banca',
  'incline bench press': 'press inclinado en banca',
  'decline bench press': 'press declinado en banca',
  'bench press with': 'press de banca con',
  'dumbbell bench press': 'press de banca con mancuernas',
  'barbell bench press': 'press de banca con barra',
  'shoulder press': 'press de hombros',
  'overhead press': 'press por encima de la cabeza',
  'military press': 'press militar',
  'arnold press': 'press Arnold',
  'floor press': 'press en el suelo',
  'incline press': 'press inclinado',
  'decline press': 'press declinado',
  'chest press': 'press de pecho',
  'leg press': 'prensa de piernas',
  'deadlift': 'peso muerto',
  'romanian deadlift': 'peso muerto rumano',
  'stiff leg deadlift': 'peso muerto piernas rígidas',
  'sumo deadlift': 'peso muerto sumo',
  'trap bar deadlift': 'peso muerto con barra hexagonal',
  'squat': 'sentadilla',
  'back squat': 'sentadilla trasera',
  'front squat': 'sentadilla frontal',
  'goblet squat': 'sentadilla copa',
  'overhead squat': 'sentadilla por encima de la cabeza',
  'bulgarian squat': 'sentadilla búlgara',
  'pistol squat': 'sentadula a una pierna',
  'box squat': 'sentadilla al cajón',
  'hack squat': 'sentadilla hack',
  'barbell squat': 'sentadilla con barra',
  'dumbbell squat': 'sentadilla con mancuernas',
  'bodyweight squat': 'sentadilla con peso corporal',
  'pull up': 'dominada',
  'pull-up': 'dominada',
  'pull ups': 'dominadas',
  'pull-ups': 'dominadas',
  'chin up': 'dominada supina',
  'chin-up': 'dominada supina',
  'chin ups': 'dominadas supinas',
  'chin-ups': 'dominadas supinas',
  'push up': 'flexión',
  'push-up': 'flexión',
  'push ups': 'flexiones',
  'push-ups': 'flexiones',
  'diamond push up': 'flexión diamante',
  'wide push up': 'flexión amplia',
  'decline push up': 'flexión declinada',
  'incline push up': 'flexión inclinada',
  'dumbbell row': 'remo con mancuerna',
  'barbell row': 'remo con barra',
  'pendlay row': 'remo Pendlay',
  't bar row': 'remo T',
  't-bar row': 'remo T',
  'cable row': 'remo en polea',
  'seated cable row': 'remo sentado en polea',
  'upright row': 'remo vertical',
  'inverted row': 'remo invertido',
  'one arm row': 'remo a un brazo',
  'single arm row': 'remo a un brazo',
  'lateral raise': 'elevación lateral',
  'side lateral raise': 'elevación lateral',
  'front raise': 'elevación frontal',
  'rear delt raise': 'elevación posterior',
  'rear delt fly': 'pájaro posterior',
  'reverse fly': 'pájaro invertido',
  'face pull': 'face pull',
  'dumbbell curl': 'curl con mancuerna',
  'barbell curl': 'curl con barra',
  'ez bar curl': 'curl con barra Z',
  'cable curl': 'curl en polea',
  'concentration curl': 'curl concentrado',
  'hammer curl': 'curl martillo',
  'preacher curl': 'curl en banco Scott',
  'incline curl': 'curl inclinado',
  'tricep pushdown': 'extensión de tríceps en polea',
  'triceps pushdown': 'extensión de tríceps en polea',
  'cable pushdown': 'extensión en polea',
  'skull crusher': 'press francés',
  'french press': 'press francés',
  'lying tricep extension': 'extensión de tríceps tumbado',
  'overhead tricep extension': 'extensión de tríceps por encima de la cabeza',
  'tricep dip': 'fondo para tríceps',
  'triceps dip': 'fondo para tríceps',
  'bench dip': 'fondo en banco',
  'dip': 'fondo',
  'dips': 'fondos',
  'parallel bar dip': 'fondo en paralelas',
  'lunges': 'zancadas',
  'lunge': 'zancada',
  'walking lunge': 'zancada caminando',
  'reverse lunge': 'zancada inversa',
  'side lunge': 'zancada lateral',
  'dumbbell lunge': 'zancada con mancuerna',
  'barbell lunge': 'zancada con barra',
  'step up': 'elevación al cajón',
  'step-up': 'elevación al cajón',
  'box jump': 'salto al cajón',
  'box jumps': 'saltos al cajón',
  'hip thrust': 'elevación de cadera',
  'glute bridge': 'puente de glúteos',
  'hip bridge': 'puente de cadera',
  'leg curl': 'curl femoral',
  'leg extension': 'extensión de cuádriceps',
  'leg raise': 'elevación de piernas',
  'hanging leg raise': 'elevación de piernas colgado',
  'lying leg raise': 'elevación de piernas tumbado',
  'calf raise': 'elevación de pantorrillas',
  'standing calf raise': 'elevación de pantorrillas de pie',
  'seated calf raise': 'elevación de pantorrillas sentado',
  'crunch': 'crunch',
  'crunches': 'crunches',
  'cable crunch': 'crunch en polea',
  'ab crunch': 'crunch abdominal',
  'reverse crunch': 'crunch inverso',
  'sit up': 'abdominal',
  'sit-up': 'abdominal',
  'sit ups': 'abdominales',
  'sit-ups': 'abdominales',
  'plank': 'plancha',
  'side plank': 'plancha lateral',
  'front plank': 'plancha frontal',
  'russian twist': 'giro ruso',
  'bicycle crunch': 'bicicleta abdominal',
  'air bike': 'bicicleta abdominal',
  'v up': 'V-up',
  'v-up': 'V-up',
  'jackknife': 'navaja',
  'mountain climber': 'escalador',
  'burpee': 'burpee',
  'burpees': 'burpees',
  'jumping jack': 'salto de tijera',
  'jumping jacks': 'saltos de tijera',
  'jump rope': 'saltar la cuerda',
  'skipping': 'saltar la cuerda',
  'treadmill': 'cinta de correr',
  'stationary bike': 'bicicleta fija',
  'exercise bike': 'bicicleta estática',
  'elliptical': 'elíptica',
  'rowing machine': 'máquina de remo',
  'stairmaster': 'escaladora',
  'kettlebell swing': 'balanceo con pesa rusa',
  'kettlebell': 'pesa rusa',
  'Turkish get up': 'levantamiento turco',
  'clean and jerk': 'cargada y envión',
  'snatch': 'arrancada',
  'power clean': 'cargada de potencia',
  'hang clean': 'cargada desde colgado',
  'push jerk': 'envión',
  'medicine ball slam': 'lanzamiento de balón medicinal',
  'medicine ball': 'balón medicinal',
  'battle rope': 'cuerda de batalla',
  'battling rope': 'cuerda de batalla',
  'sandbag': 'saco de arena',
  'farmer walk': 'caminata del granjero',
  'farmer carry': 'carga del granjero',
  'suitcase carry': 'carga maletero',
  'bear crawl': 'gateo oso',
  'crab walk': 'caminata del cangrejo',
  'duck walk': 'caminata del pato',
  'inchworm': 'gusano',
  'wall sit': 'sentadilla contra la pared',
  'good morning': 'buenos días',
  'hyperextension': 'hiperextensión',
  'back extension': 'extensión de espalda',
  'superman': 'superman',
  'bird dog': 'pájaro-perro',
  'dead bug': 'insecto muerto',
  'rollout': 'rodamiento',
  'ab rollout': 'rodamiento abdominal',
  'wheel rollout': 'rodamiento con rueda',
  'stretch': 'estiramiento',
  'stretching': 'estiramiento',
  'warm up': 'calentamiento',
  'cool down': 'enfriamiento',
  'foam rolling': 'liberación miofascial',
  'foam roll': 'rodillo de espuma',
  'mobilization': 'movilización',
  'mobility': 'movilidad',
  'rotation': 'rotación',
  'hold': 'mantención',
  'isometric': 'isométrico',
  'pallof press': 'press Pallof',
  'neck': 'cuello',
  'neck stretch': 'estiramiento de cuello',
  'shoulder tap': 'toque de hombro',
  'hip flexor': 'flexor de cadera',
  'hip circle': 'círculo de cadera',
  'clamshell': 'almeja',
  'donkey kick': 'patada de burro',
  'fire hydrant': 'boca de incendio',
  'glute kickback': 'patada de glúteo',
  'leg lift': 'elevación de pierna',
  'side leg raise': 'elevación lateral de pierna',
  'inner thigh': 'aducción de pierna',
  'adductor': 'aductor',
  'abductor': 'abductor',
  'calf stretch': 'estiramiento de gemelos',
  'hamstring stretch': 'estiramiento de isquiotibiales',
  'quad stretch': 'estiramiento de cuádriceps',
  'chest stretch': 'estiramiento de pecho',
  'tricep stretch': 'estiramiento de tríceps',
  'shoulder stretch': 'estiramiento de hombro',
  'lat stretch': 'estiramiento de dorsal',
  'glute stretch': 'estiramiento de glúteos',
  'hip stretch': 'estiramiento de cadera',
  'groin stretch': 'estiramiento de ingle',
  'pigeon pose': 'postura de la paloma',
  'child pose': 'postura del niño',
  'downward dog': 'perro boca abajo',
  'upward dog': 'perro boca arriba',
  'cat cow': 'gato-vaca',
  'cobra': 'cobra',
  'bridge': 'puente',
  'butterfly': 'mariposa',
  'yoga': 'yoga',
  'pilates': 'pilates',
  'bodyweight': 'peso corporal',
  'banded': 'con banda',
  'weighted': 'con peso',
  'assisted': 'asistido',
  'unilateral': 'unilateral',
  'alternating': 'alternado',
  'single leg': 'a una pierna',
  'single arm': 'a un brazo',
  'both arms': 'ambos brazos',
  'bilateral': 'bilateral',
  'wide grip': 'agarre amplio',
  'narrow grip': 'agarre estrecho',
  'close grip': 'agarre cerrado',
  'reverse grip': 'agarre inverso',
  'neutral grip': 'agarre neutro',
  'underhand': 'supino',
  'overhand': 'pronado',
  'palms up': 'palmas arriba',
  'palms down': 'palmas abajo',
  'straight arm': 'brazo recto',
  'bent arm': 'brazo flexionado',
  'bent over': 'inclinado',
  'seated': 'sentado',
  'standing': 'de pie',
  'lying': 'tumbado',
  'prone': 'boca abajo',
  'supine': 'boca arriba',
  'kneeling': 'arrodillado',
  'half kneeling': 'medio arrodillado',
  'side lying': 'tumbado de lado',
  'four point': 'a cuatro patas',
  'all fours': 'a cuatro patas',
  'on knees': 'de rodillas',
  'flat': 'plano',
  'incline': 'inclinado',
  'decline': 'declinado',
  'vertical': 'vertical',
  'horizontal': 'horizontal',
  'lateral': 'lateral',
  'frontal': 'frontal',
  'posterior': 'posterior',
  'anterior': 'anterior',
  'medial': 'medial',
  'external': 'externo',
  'internal': 'interno',
  'right': 'derecho',
  'left': 'izquierdo',
  'both': 'ambos',
  'alternate': 'alternado',
  'alternating': 'alternado',
  'heel touchers': 'toque de talones',
  'pulldown': 'jalón',
  'lat pulldown': 'jalón dorsal',
  'straight arm pulldown': 'jalón brazo recto',
  'trunk rotation': 'rotación de tronco',
  'trunk twist': 'giro de tronco',
  'side bend': 'flexión lateral',
  'side bends': 'flexiones laterales',
  'overhead': 'por encima de la cabeza',
  'underhand': 'supino',
  'overhand': 'pronado',
  'mixed grip': 'agarre mixto',
  'ankle circles': 'círculos de tobillo',
  'ankle': 'tobillo',
  'wrist circles': 'círculos de muñeca',
  'arm circles': 'círculos de brazo',
  'shoulder circles': 'círculos de hombro',
  'hip circles': 'círculos de cadera',
  'neck circles': 'círculos de cuello',
  'circle': 'círculo',
  'circles': 'círculos',
  'arm slinger': 'balanceo de brazos',
  'arm slingers': 'balanceo de brazos',
  'hanging': 'colgado',
  'knee': 'rodilla',
  'knees': 'rodillas',
  'toe touch': 'toque de puntas',
  'toe touches': 'toque de puntas',
  'heel touch': 'toque de talones',
  'hands': 'manos',
  'feet': 'pies',
  'elbow': 'codo',
  'elbows': 'codoso',
  'wrist': 'muñeca',
  'wrists': 'muñecas',
  'shoulder': 'hombro',
  'shoulders': 'hombros',
  'ankle': 'tobillo',
  'ankles': 'tobillos',
  'hip': 'cadera',
  'hips': 'caderas',
  'knee': 'rodilla',
  'knees': 'rodillas',
  'thigh': 'muslo',
  'thighs': 'muslos',
  'heel': 'talón',
  'heels': 'talones',
  'toe': 'dedo del pie',
  'toes': 'dedos del pie',
  'forearm': 'antebrazo',
  'forearms': 'antebrazos',
  'upper arm': 'brazo superior',
  'lower arm': 'antebrazo',
  'upper leg': 'muslo',
  'lower leg': 'pierna inferior',
  'inner thigh': 'parte interna del muslo',
  'outer thigh': 'parte externa del muslo',
  'rear': 'posterior',
  'front': 'anterior',
  'squad': 'sentadilla',
  'side': 'lateral',
  'top': 'superior',
  'bottom': 'inferior',
  'upper': 'superior',
  'lower': 'inferior',
  'legs': 'piernas',
  'on': 'sobre',
  'ball': 'pelota',
  'exercise ball': 'pelota de ejercicio',
  'stability ball': 'pelota de estabilidad',
  'ups': 'elevaciones',
  'kickback': 'patada',
  'kickbacks': 'patadas',
  'pushdown': 'extensión',
  'pushdowns': 'extensiones',
  'pullover': 'pullover',
  'cross': 'cruz',
  'crossovers': 'cruces',
  'crossover': 'cruce',
  'squatting': 'en cuclillas',
  'high': 'alta',
  'low': 'baja',
  'in': 'en',
  'out': 'fuera',
  'up': 'arriba',
  'down': 'abajo',
  'open': 'abierto',
  'closed': 'cerrado',
  'long': 'largo',
  'short': 'corto',
  'big': 'grande',
  'small': 'pequeño',
  'fast': 'rápido',
  'quick': 'rápido',
  'head': 'cabeza',
  'arm': 'brazo',
  'foot': 'pie',
  'finger': 'dedo',
  'fingers': 'dedos',
  'calf': 'gemelo',
  'calves': 'gemelos',
  'chest': 'pecho',
  'full': 'completo',
  'apart': 'separados',
  'male': '',
  'dead': 'muerto',
  'with': 'con',
  'and': 'y',
  'forward': 'hacia adelante',
  'backward': 'hacia atrás',
  'lever': 'palanca',
  'motion': 'movimiento',
  'parallel': 'paralelo',
  'gluteus': 'glúteo',
  'piriformis': 'piramidal',
  'hamstring': 'isquiotibial',
  'rectus femoris': 'recto femoral',
  'pectoralis major': 'pectoral mayor',
  'bent': 'flexionado',
  'turned': 'girado',
  'outward': 'hacia afuera',
  'inward': 'hacia adentro',
  'aerial': 'aéreo',
  'arch': 'arco',
  'around': 'alrededor',
  'between': 'entre',
  'half': 'media',
  'jack': 'jack',
  'knee': 'rodilla',
  'normal': 'normal',
  'oblique': 'oblicuo',
  'one': 'uno',
  'only': 'solo',
  'over': 'sobre',
  'pole': 'palo',
  'reverse': 'invertido',
  'round': 'redondo',
  'sit': 'sentado',
  'skater': 'patinador',
  'slow': 'lento',
  'speed': 'velocidad',
  'sprawl': 'sprawl',
  'sprint': 'esprint',
  'star': 'estrella',
  'support': 'soporte',
  'three': 'tres',
  'tuck': 'tuck',
  'turn': 'giro',
  'upward': 'hacia arriba',
  'downward': 'hacia abajo',
  'weight': 'peso',
  'without': 'sin',
  'world': 'mundo',
  'greatest': 'mayor',
  'show': 'mostrar',
  'athletic': 'atlético',
  'straight': 'recto',
  'middle': 'medio',
  'inner': 'interno',
  'outer': 'externo',
  'close': 'cerrado',
  'wide': 'amplio',
  'narrow': 'estrecho',
  'straight': 'recto',
  'bent': 'flexionado',
  'extended': 'extendido',
  'flexed': 'flexionado',
  'twist': 'giro',
  'rotation': 'rotación',
  'curl': 'curl',
  'extension': 'extensión',
  'flexion': 'flexión',
  'abduction': 'abducción',
  'adduction': 'aducción',
  'press': 'press',
  'pull': 'jalón',
  'push': 'empuje',
  'raise': 'elevación',
  'row': 'remo',
  'fly': 'apertura',
  'flies': 'aperturas',
  'flyes': 'aperturas',
  'swing': 'balanceo',
  'slam': 'lanzamiento',
  'throw': 'lanzamiento',
  'catch': 'recepción',
  'hop': 'salto',
  'jump': 'salto',
  'skip': 'salto',
  'bound': 'salto',
  'sprint': 'esprint',
  'run': 'correr',
  'walk': 'caminar',
  'crawl': 'gatear',
  'climb': 'trepar',
  'drag': 'arrastre',
  'carry': 'carga',
  'hold': 'sujeción',
  'lift': 'levantamiento',
  'lower': 'descenso',
  'raise': 'elevación',
  'roll': 'rodar',
  'slide': 'deslizar',
  'spin': 'girar',
  'kick': 'patada',
  'step': 'paso',
  'tap': 'toque',
  'touch': 'toque',
  'point': 'punta',
};

const MUSCLE_TRANSLATIONS = {
  'abductors': 'Abductores',
  'abs': 'Abdominales',
  'adductors': 'Aductores',
  'biceps': 'Bíceps',
  'brachialis': 'Braquial',
  'calves': 'Gemelos',
  'cardiovascular system': 'Sistema Cardiovascular',
  'core': 'Core',
  'deltoid': 'Deltoides',
  'deltoids': 'Deltoides',
  'erector spinae': 'Erector Espinal',
  'forearms': 'Antebrazos',
  'glutes': 'Glúteos',
  'gluteal': 'Glúteos',
  'hamstrings': 'Isquiotibiales',
  'hip flexors': 'Flexores de Cadera',
  'inner thighs': 'Aductores',
  'lats': 'Dorsales',
  'latissimus dorsi': 'Dorsal Ancho',
  'levator scapulae': 'Elevador de la Escápula',
  'lower back': 'Zona Lumbar',
  'neck': 'Cuello',
  'obliques': 'Oblicuos',
  'pectorals': 'Pectorales',
  'quadriceps': 'Cuádriceps',
  'quads': 'Cuádriceps',
  'rhomboids': 'Romboides',
  'serratus anterior': 'Serrato Anterior',
  'spine': 'Columna',
  'trapezius': 'Trapecio',
  'traps': 'Trapecio',
  'triceps': 'Tríceps',
  'triceps brachii': 'Tríceps Braquial',
  'upper back': 'Espalda Alta',
  'vastus lateralis': 'Vasto Lateral',
  'vastus medialis': 'Vasto Medial',
  'soleus': 'Sóleo',
  'gastrocnemius': 'Gastrocnemio',
  'iliopsoas': 'Iliopsoas',
  'psoas': 'Psoas',
  'teres major': 'Teres Mayor',
  'teres minor': 'Teres Menor',
  'infraspinatus': 'Infraespinoso',
  'supraspinatus': 'Supraespinoso',
  'subscapularis': 'Subescapular',
  'sartorius': 'Sartorio',
  'gracilis': 'Grácil',
  'pectineus': 'Pectíneo',
  'tensor fasciae latae': 'Tensor de la Fascia Lata',
  'tfl': 'Tensor de la Fascia Lata',
  'adductor brevis': 'Aductor Corto',
  'adductor longus': 'Aductor Largo',
  'adductor magnus': 'Aductor Mayor',
  'biceps femoris': 'Bíceps Femoral',
  'semimembranosus': 'Semimembranoso',
  'semitendinosus': 'Semitendinoso',
  'tibialis anterior': 'Tibial Anterior',
  'tibialis posterior': 'Tibial Posterior',
  'peroneals': 'Peroneos',
  'fibularis': 'Peroneo',
  'flexor digitorum': 'Flexor de los Dedos',
  'extensor digitorum': 'Extensor de los Dedos',
  'wrist flexors': 'Flexores de Muñeca',
  'wrist extensors': 'Extensores de Muñeca',
  'hip': 'Cadera',
  'groin': 'Ingle',
  'chest': 'Pecho',
};

const EQUIPMENT_TRANSLATIONS = {
  'body weight': 'Peso Corporal',
  'bodyweight': 'Peso Corporal',
  'dumbbell': 'Mancuerna',
  'dumbbells': 'Mancuernas',
  'barbell': 'Barra',
  'kettlebell': 'Pesa Rusa',
  'kettlebells': 'Pesas Rusas',
  'cable': 'Polea',
  'cables': 'Poleas',
  'machine': 'Máquina',
  'band': 'Banda Elástica',
  'bands': 'Bandas Elásticas',
  'resistance band': 'Banda de Resistencia',
  'resistance bands': 'Bandas de Resistencia',
  'medicine ball': 'Balón Medicinal',
  'exercise ball': 'Pelota de Ejercicio',
  'stability ball': 'Pelota de Estabilidad',
  'swiss ball': 'Pelota Suiza',
  'foam roll': 'Rodillo de Espuma',
  'ez barbell': 'Barra Z',
  'ez curl bar': 'Barra Z',
  'trap bar': 'Barra Hexagonal',
  'smith machine': 'Máquina Smith',
  'sled': 'Trineo',
  'bench': 'Banco',
  'pull-up bar': 'Barra de Dominadas',
  'parallel bars': 'Barras Paralelas',
  'paralettes': 'Paralettes',
  'step': 'Step',
  'box': 'Cajón',
  'plyo box': 'Cajón Plio',
  'wheel': 'Rueda',
  'ab wheel': 'Rueda Abdominal',
  'roller': 'Rodillo',
  'rope': 'Cuerda',
  'jump rope': 'Cuerda para Saltar',
  'towel': 'Toalla',
  'yoga block': 'Bloque de Yoga',
  'mat': 'Colchoneta',
  'plate': 'Disco',
  'weight plate': 'Disco',
  'battle rope': 'Cuerda de Batalla',
  'slam ball': 'Balón de Slam',
  'sandbag': 'Saco de Arena',
  'clubbell': 'Clubbell',
  'tire': 'Llanta',
  'dip bar': 'Barra de Fondos',
  'dip bars': 'Barras de Fondos',
  'chin-up bar': 'Barra de Dominadas Supinas',
  'leg extension machine': 'Máquina de Extensión de Piernas',
  'leg curl machine': 'Máquina de Curl Femoral',
  'pec deck': 'Pec Deck',
  'lat pulldown machine': 'Máquina de Dorsales',
  't-bar row': 'Remo T-Bar',
  'power rack': 'Jaula de Potencia',
  'squat rack': 'Jaula de Sentadillas',
  'stationary bike': 'Bicicleta Fija',
  'treadmill': 'Cinta de Correr',
  'elliptical': 'Elíptica',
  'stairmaster': 'Escaladora',
  'rowing machine': 'Máquina de Remo',
  'ski erg': 'Ergómetro de Esquí',
  'assisted': 'Asistido',
  'weighted': 'Con Peso',
  'other': 'Otro',
  'none': 'Ninguno',
};

function applyTranslation(text, translations, minWordLen = 2) {
  if (!text) return text;
  let result = text;

  const sorted = Object.entries(translations).sort((a, b) => b[0].length - a[0].length);
  for (const [en, es] of sorted) {
    const regex = new RegExp(`\\b${en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    if (regex.test(result)) {
      result = result.replace(regex, (match) => {
        const isFirstUpper = match[0] === match[0].toUpperCase();
        const word = isFirstUpper
          ? es.charAt(0).toUpperCase() + es.slice(1)
          : es;
        return word;
      });
    }
  }

  return result;
}

function translateName(name) {
  let result = name.toLowerCase().trim();

  // Aplicar traducciones compuestas primero (ordenadas de más largas a más cortas)
  result = applyTranslation(result, EXERCISE_NAME_TRANSLATIONS);

  // Capitalizar primera letra
  result = result.charAt(0).toUpperCase() + result.slice(1);

  return result;
}

function translateMuscles(text) {
  return applyTranslation(text, MUSCLE_TRANSLATIONS);
}

function translateEquipment(text) {
  return applyTranslation(text, EQUIPMENT_TRANSLATIONS);
}

function main() {
  console.log('📖 Leyendo dataset...');
  const raw = fs.readFileSync(INPUT_JSON, 'utf8');
  let exercises = JSON.parse(raw);
  console.log(`   ${exercises.length} ejercicios cargados.\n`);

  console.log('🔤 Traduciendo nombres de ejercicios...');
  let nameChanges = 0;
  for (const ex of exercises) {
    const original = ex.name;
    ex.name = translateName(ex.name);
    if (original !== ex.name) nameChanges++;
  }
  console.log(`   ${nameChanges} nombres traducidos.\n`);

  console.log('🔤 Traduciendo músculos secundarios...');
  for (const ex of exercises) {
    ex.secondaryMuscles = translateMuscles(ex.secondaryMuscles);
  }
  console.log('   ✅ Hecho.\n');

  console.log('🔤 Traduciendo equipamiento...');
  for (const ex of exercises) {
    ex.equipment = translateEquipment(ex.equipment);
  }
  console.log('   ✅ Hecho.\n');

  console.log('🔤 Traduciendo target...');
  for (const ex of exercises) {
    ex.target = translateMuscles(ex.target);
  }
  console.log('   ✅ Hecho.\n');

  // Guardar
  fs.writeFileSync(INPUT_JSON, JSON.stringify(exercises, null, 0), 'utf8');
  const sizeMB = (fs.statSync(INPUT_JSON).size / 1024 / 1024).toFixed(2);
  console.log(`💾 Guardado: ${INPUT_JSON} (${sizeMB} MB, ${exercises.length} ejercicios)`);

  // Mostrar algunos ejemplos
  console.log('\n📝 Ejemplos de traducción:');
  for (let i = 0; i < Math.min(10, exercises.length); i++) {
    console.log(`   ${exercises[i].id}: ${exercises[i].name}`);
  }
  console.log('\n🎉 ¡Traducción completada!');
}

main();
